### ISSUE TITLE
您的网站好像不能访问了

### ISSUE THREAD

**Issue by yihong0618** [shuhari/500lines-rewrite#1]
前辈您好，
今天发现您的网站里面的文章全部报 500 了~

**Comment by shuhari** [comment]
感谢提醒，已修复。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: yihong<mailto:notifications@github.com>
发送时间: 2021年2月9日 9:02
收件人: shuhari/500lines-rewrite<mailto:500lines-rewrite@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [shuhari/500lines-rewrite] 您的网站好像不能访问了 (#1)


前辈您好，
今天发现您的网站里面的文章全部报 500 了~

―
